functionsDirectory = "C:\\Users\\micro\\Documents\\Code\\netlify\\instagram-serverless\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\micro\\Documents\\Code\\netlify\\instagram-serverless"
publishOrigin = "default"
commandOrigin = "config"
command = "npm install"
functions = "C:\\Users\\micro\\Documents\\Code\\netlify\\instagram-serverless\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]